[project]
name = "rag"
version = "0.1.0"
description = "RAG Against The Machine"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "bm25s>=0.3.9",
    "fire>=0.7.1",
    "llama-cpp-python>=0.3.23",
    "pydantic>=2.13.4",
    "tqdm>=4.67.3",
]

[dependency-groups]
dev = [
    "types-tqdm>=4.67.3.20260518",
]