import uuid
from typing import List, Union
from pydantic import BaseModel, Field


class MinimalSource(BaseModel):
    """Represents a minimal source location of information.

    Attributes:
        file_path: The full path to the source file.
        first_character_index: The starting character position.
        last_character_index: The ending character position.
    """

    file_path: str
    first_character_index: int
    last_character_index: int


class UnansweredQuestion(BaseModel):
    """Represents a question without a baseline answer.

    Attributes:
        question_id: A unique identifier, auto-generated by default.
        question: The natural language question text.
    """

    question_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    question: str


class AnsweredQuestion(UnansweredQuestion):
    """Represents a question paired with its ground-truth sources.

    Attributes:
        sources: A list of correct source locations.
        answer: The ground-truth answer text.
    """

    sources: List[MinimalSource]
    answer: str


class RagDataset(BaseModel):
    """Represents a dataset collection of RAG questions.

    Attributes:
        rag_questions: A list of answered or unanswered questions.
    """

    rag_questions: List[Union[AnsweredQuestion, UnansweredQuestion]]


class MinimalSearchResults(BaseModel):
    """Represents retrieved sources for a specific question id.

    Attributes:
        question_id: The unique identifier of the queried question.
        question: The natural language question text.
        retrieved_sources: A list of predicted relevant source locations.
    """

    question_id: str
    question_str: str
    retrieved_sources: List[MinimalSource]


class MinimalAnswer(MinimalSearchResults):
    """Represents search results augmented with a generated LLM answer.

    Attributes:
        answer: The natural language answer generated by the model.
    """

    answer: str


class StudentSearchResults(BaseModel):
    """Mandatory output format for pure retrieval operations.

    Attributes:
        search_results: A list of minimal search results per question.
        k: The number of requested top results.
    """

    search_results: List[MinimalSearchResults]
    k: int


class StudentSearchResultsAndAnswer(StudentSearchResults):
    """Mandatory output format for full RAG generations.

    Attributes:
        search_results: A list of minimal answers containing predictions.
    """

    search_results: List[MinimalAnswer]


class ChunkStorage(BaseModel):
    """Internal model linking a target source to its raw text string.

    Attributes:
        source: The official MinimalSource meta-information.
        text_content: The actual raw text slice from the file.
    """

    source: MinimalSource
    text_content: str
